Repository ministation/space-station-14, pull requests merged in 2025-04, with the labels that each got.

#5 [ADD] Добавлены скрипты для билда сборки и её быстрого запуска.
  Scripts/bat/!README.txt
  Scripts/bat/buildAllDebug.bat
  Scripts/bat/buildAllRelease.bat
  Scripts/bat/buildAllTools.bat
  Scripts/bat/runQuickAll.bat
  Scripts/bat/runQuickClient.bat
  Scripts/bat/runQuickServer.bat
  Scripts/bat/runTests.bat
  Scripts/bat/runTestsIntegration.bat
  Scripts/bat/runTestsYAML.bat
  Scripts/sh/!README.txt
  Scripts/sh/buildAllDebug.sh
  Scripts/sh/buildAllRelease.sh
  Scripts/sh/buildAllTools.sh
  Scripts/sh/runQuickAll.sh
  Scripts/sh/runQuickClient.sh
  Scripts/sh/runQuickServer.sh
  Scripts/sh/runTests.sh
  Scripts/sh/runTestsIntegration.sh
  Scripts/sh/runTestsYAML.sh
Labels: Changes: No C#

#8 [TWEAK] Blueshield tweaks
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/_DeadSpace/Roles/Jobs/Command/officer_blueshield.yml
  Resources/Prototypes/_Mini/Entities/Objects/Weapons/Guns/Ammunition/Magazines/light_rifle.yml
  Resources/Prototypes/_Mini/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
  Resources/Prototypes/_Mini/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/_Mini/tags.yml
Labels: Changes: No C#

#10 Одежда/фикс рюкзака (Теперь должен работать не только на локалке)
  Resources/Prototypes/_Mini/Clothing/Back/backpacks.yml
  Resources/Prototypes/_Mini/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.yml/equipped-INNERCLOTHING.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.yml/icon.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.yml/inhand-left.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.yml/inhand-right.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.yml/meta.json
Labels: Changes: No C#

#13 GitHub workflows
  .github/workflows/benchmarks.yml
  .github/workflows/build-docfx.yml
  .github/workflows/build-map-renderer.yml
  .github/workflows/build-test-debug.yml
  .github/workflows/check-crlf.yml
  .github/workflows/labeler-review.yml
  .github/workflows/publish-testing.yml
  .github/workflows/publish.yml
  .github/workflows/rsi-diff.yml
  .github/workflows/test-packaging.yml
  .github/workflows/update-credits.yml
  .github/workflows/validate-rgas.yml
  .github/workflows/validate-rsis.yml
  .github/workflows/validate_mapfiles.yml
  .github/workflows/yaml-linter.yml
Labels: Changes: No C#

#14 Update janidrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
Labels: Changes: No C#

#15 фикс одежды (последний)
  Resources/Prototypes/_Mini/Clothing/Back/backpacks.yml
  Resources/Prototypes/_Mini/Clothing/Uniforms/jumpsuits.yml
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/ClothingCultAcolit.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/ClothingCultAcolit.rsi/icon.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/ClothingCultAcolit.rsi/inhand-left.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/ClothingCultAcolit.rsi/inhand-right.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/ClothingCultAcolit.rsi/meta.json
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.rsi/icon.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.rsi/inhand-left.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.rsi/inhand-right.png
  Resources/Textures/_Mini/Clothing/Uniforms/Jumpsuit/WinRar.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites

#16 [TWEAK] Idk bugfix
  .github/workflows/labeler-size.yml
  Resources/Maps/barratry.yml
  Resources/Maps/elkridge.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/Entities/Structures/hydro_tray.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/_ADT/Entities/Clothing/OuterClothing/fem_syndie.yml
  Resources/Prototypes/_ADT/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_DeadSpace/Demons/demons.yml
  Resources/Prototypes/_DeadSpace/Demons/herald.yml
  Resources/Prototypes/_DeadSpace/Entities/Mobs/NPCs/poly.yml
  Resources/Prototypes/_DeadSpace/Entities/Mobs/NPCs/xenomaid.yml
  Resources/Prototypes/_DeadSpace/Spiders/spiders.yml
  Resources/Prototypes/_DeadSpace/security_borg.yml
  Resources/Prototypes/_Mini/Recipes/Lathes/Packs/security.yml
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/bolt-open.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/mag-0.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_box.rsi/wielded-inhand-right.png
Labels: Changes: Map, Changes: No C#, Changes: Sprites

#17 Удаление инициализиированных предметов на Barratry.yml
  .github/workflows/labeler-untriaged.yml
  Resources/Maps/barratry.yml
Labels: Changes: Map, Changes: No C#, size/M

#22 [WORKFLOW] незначительное изменение RSI DIFF
  .github/workflows/rsi-diff.yml
Labels: Changes: No C#, size/XS, S: Untriaged

#25 Ds authorization
  Content.Client/Lobby/UI/LobbyGui.xaml
  Content.Client/Lobby/UI/LobbyGui.xaml.cs
  Content.Shared/Corvax/CCCVars/CCCVars.cs
Labels: size/S, Changes: UI, Changes: C#, S: Untriaged

#26 Шаттл химиков для ивента
  Resources/Maps/Shuttles/shuttle_breaking_bad.yml
Labels: Changes: Map, Changes: No C#, size/L, S: Untriaged

#24 [REMOVE] [TWEAK] ремапп Silly, удаление Barratry, удаление Elkridge
  Resources/Maps/barratry.yml
  Resources/Maps/ds_silly.yml
  Resources/Maps/elkridge.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/barratry.yml
Labels: Changes: Map, Changes: No C#, size/XL, S: Untriaged
